### ISSUE TITLE
[Feature Request] Option to not remove containers upon completion (Act equivalent: --reuse)

### ISSUE THREAD

**Issue by JustinGrote** [ChristopherHX/runner.server#30]
## Feature Summary
If a Github Action fails, it is often very useful to connect into the container that was running the action to check status of files, do some interactive debugging, etc. to find out what happened rather than trial-and-error of running the containers.

act has an option `--reuse` which simply does not remove the containers after they are executed, a similar option should be added for this runner

Great work! This is really impressive.

**Comment by ChristopherHX** [comment]
Wouldn't it be better to integrate a Telnet / ssh tunnel next to the failed step?
It is easy to inject steps like I did with `localcheckout@v1`, this would also work with non docker containers.

**Comment by JustinGrote** [comment]
I use the upterm action for this in "real" GitHub Actions so I suppose that would be sufficient to "stall" a container and attach a shell.

**Comment by ChristopherHX** [comment]
If it is sufficient to just remove `--rm` from docker run, I do it now.
I thought, that reuse means that the runner itself reuses abandoned containers in a job retry.

**Comment by JustinGrote** [comment]
Yep that's all I was thinking. Thanks!

**Comment by ChristopherHX** [comment]
`--keep-container` should keep docker container, workdir and container network, therefore also needs to recreate runners after a job finishs.

These feature may sometimes loose jobs, if you are have more than `--parallel` jobs. Althought it seems to work for me on windows without that problem.

```pwsh
PS C:\Users\Christopher\bug_29> docker ps
CONTAINER ID   IMAGE                            COMMAND               CREATED          STATUS          PORTS     NAMES
4c83c3e0d9fe   catthehacker/ubuntu:act-latest   "tail -f /dev/null"   50 seconds ago   Up 35 seconds             c31b1d937a16411bb6f1fd4b663f12b1_catthehackerubuntuactlatest_0b2343
f9e0268d6114   catthehacker/ubuntu:act-latest   "tail -f /dev/null"   50 seconds ago   Up 35 seconds             57846543eefd43a4a9a33530295f48b3_catthehackerubuntuactlatest_ccb40a
290176a9d457   catthehacker/ubuntu:act-latest   "tail -f /dev/null"   50 seconds ago   Up 35 seconds             dddce8ee4c3441c6b7be393522e715a7_catthehackerubuntuactlatest_9f7e6a
d20b275f8188   catthehacker/ubuntu:act-latest   "tail -f /dev/null"   50 seconds ago   Up 36 seconds             c5c54a35ab284c10b2e289d74b5f8c82_catthehackerubuntuactlatest_357674
00ce6c277103   ubuntu:latest                    "tail -f /dev/null"   6 minutes ago    Up 6 minutes              d18256beaccf4f45b3527dedde735c30_ubuntulatest_4e4749
8d076eaff2cc   ubuntu:latest                    "tail -f /dev/null"   6 minutes ago    Up 6 minutes              7ee3450c7eba4ca8b6009e9ae71cfadb_ubuntulatest_1fabf3
7e4e7ccb4c90   ubuntu:latest                    "tail -f /dev/null"   6 minutes ago    Up 6 minutes              dc9ee34c112440b9844182554aa7bc5d_ubuntulatest_31da63
46edb85bc7c4   ubuntu:latest                    "tail -f /dev/null"   6 minutes ago    Up 6 minutes              e8be6c27d9534301900f54389fd180f5_ubuntulatest_0c7b6e
```
