### ISSUE TITLE
[Feature Request] Publish as dotnet global tool

### ISSUE THREAD

**Issue by JustinGrote** [ChristopherHX/runner.server#31]
**Describe the enhancement**
Having the runner (along with the self-starting Server) available as a dotnet global tool would make distribution and usage of the app much simpler.

`dotnet-gharunner -v -W path/to/my/workflow`

https://medium.com/it-dead-inside/building-custom-tools-into-dotnet-core-1c44c7baa7ad

**Comment by JustinGrote** [comment]
@ChristopherHX does it need to ship node natively if you're not doing self-runners (since you pull containers with node in them)? Could it fetch-on-demand?

**Comment by ChristopherHX** [comment]
> since you pull containers with node in them

I want to keep changes to runner behavior minimal and using node12 from the docker image in a docker container is a huge change.
You can use node12 actions inside ubuntu:latest (it does not have node).
The official runner uses it's own version of node, only act uses node from the container.

> fetch-on-demand

Would be a good option, also keeps the nuget package smaller.

**Comment by JustinGrote** [comment]
@ChristopherHX
> Would be a good option, also keeps the nuget package smaller.

Yes extracting the zip takes quite a while on my machine and I think it's due to the two nodejs distributions included.

**Comment by ChristopherHX** [comment]
@JustinGrote I created a preview version on nuget.org

It has only 24MB and downloads node12 while running the first nodejs action. Node12 of the runner won't receive as much updates as the runner. You only need the dotnet 5.0.x sdk.
https://www.nuget.org/packages/io.github.christopherhx.gharun/3.1.2-preview.2021.6.16.22.1.58.944414936

**Comment by JustinGrote** [comment]
@ChristopherHX Nice! I'll check it out when I get a moment.

**Comment by JustinGrote** [comment]
@ChristopherHX sorry for the delay, got a chance to test it today and seems to work great! Thank you.

**Comment by ChristopherHX** [comment]
@JustinGrote Good to hear that the nuget package works for you.
Once github releases the big composite action update (with uses in composite) this runner has no problems to merge the feature.

_I wonder why my preview test packages (with some big bugs, like require the most recent net5 sdk) has much more downloads than the final release._

**Comment by JustinGrote** [comment]
@ChristopherHX somebody's CI maybe?

**Comment by ChristopherHX** [comment]
> somebody's CI maybe?

Oh that make sense, especially as nuget preview packages needs to be downloaded via an explicit version.
