### ISSUE TITLE
Add ability to override the Agents directory due to Windows max path limit of 260 characters....

### ISSUE THREAD

**Issue by acotty** [ChristopherHX/runner.server#85]
**Describe the enhancement**
I am getting a failure when running via the following command:
.\bin\Runner.Client.exe --workflow .github\workflows\Windows-continuous-integration.yml --event push --payload CB_test.json -P windows-2019=-self-hosted --keep-runner-directory

I have tracked it possibly down to an issue with the MSYS2 packages adhering to the dumb MS max path spec of 260characters. Some reports of this on MSYS2 are:
https://github.com/msys2/MINGW-packages/issues/3139
https://sourceforge.net/p/mingw/bugs/2347/

**Code Snippet**
In the https://github.com/ChristopherHX/runner.server/blob/main/src/Runner.Client/Program.cs the existing code is:
```
            var agentname = $"Agent-{Guid.NewGuid().ToString()}";
            string tmpdir = Path.Combine(GitHub.Runner.Sdk.GharunUtil.GetLocalStorage(), "Agents", agentname);

```
It would be nice to be able to specify the tmpdir so I can set it to say C:\BUILD_TEST as building in windows works

**Additional information**
The directory structure created via the .\bin\Runner.Client.exe  and workflow file is:
C:\Users\andrew\AppData\Local\gharun\Agents\Agent-b941df27-13a6-4b05-906e-00eadca29031\_work\CodeBlocks_Unofficial_Testing\CodeBlocks_Unofficial_Testing\CodeBlocks\src\plugins\contrib\wxContribItems\wxFlatNotebook\

Building locally the following directory works:
D:\Andrew_Development\Work_Installers\CodeBLocks_Private_Experimental\src\plugins\contrib\wxContribItems\wxFlatNotebook

**Comment by ChristopherHX** [comment]
Good point, I actually never used this tool to build bigger opensource projects on windows.
Actually `Agents\Agent-b941df27-13a6-4b05-906e-00eadca29031\_work` is a bit long, something like `a\w143kxnu.idj\w` seem to be shorter and allows more usecases to pass.

I consider adding this to milestone 3.9.0, but you will only be able to change the `C:\Users\<username>\AppData\Local\gharun\Agents` path. It is possible to spawn multiple runners via `--parallel 2`, which cannot share it's folder with other instances.

On the other hand https://github.com/ChristopherHX/runner.server#advanced-usage allows you to configure the official runner https://github.com/actions/runner/releases/latest in the folder of your choice.
- start the server
- configure the runner in `C:\runner`
- point `Runner.Client` / `gharun` with the `--server` option to the instance.

**Comment by acotty** [comment]
Thanks for the info. I will try the runner.server after I get the NSIS installation creation working.
