### ISSUE TITLE
bin\Runner.Server does not appear to use the MemoryDB if no external sqlite is specified

### ISSUE THREAD

**Issue by acotty** [ChristopherHX/runner.server#89]
**Describe the bug**
If I have read the code in https://github.com/ChristopherHX/runner.server/blob/main/src/Runner.Server/Startup.cs and the documentation correctly, but I could be wrong, then the code does not for some unknown reason not use the "conf.UseInMemoryDatabase("Agents");"

I get the following error and info:
```
$ bin\Runner.Server --urls http://localhost                                                                                                
Relational-specific methods can only be used when the context is using a relational database provider.                                     
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.GetRelationalService[TService](IInfrastructure`1 databaseFacade)    
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)                              
   at Runner.Server.Startup.ConfigureServices(IServiceCollection services)                                                                 
info: Microsoft.Hosting.Lifetime[14]                                                                                                       
      Now listening on: http://localhost:80                                                                                                
info: Microsoft.Hosting.Lifetime[0]                                                                                                        
      Application started. Press Ctrl+C to shut down.                                                                                      
info: Microsoft.Hosting.Lifetime[0]                                                                                                        
      Hosting environment: Production                                                                                                      
info: Microsoft.Hosting.Lifetime[0]                                                                                                        
      Content root path: C:\actions-runner\bin                                                                                             

```
**To Reproduce**
Run the following 
    bin\Runner.Server --urls http://localhost
In the C:\actions-runner directory with no specific configuration files.

**Expected behavior**
The bin\Runner.Server --urls http://localhost to not cause a DB error to show.

I have not tried to configure the server to use SQLLite .

## Runner Version and Platform
$ .\bin\Runner.Client.exe --version
3.8.0

OS info:
Windows 10 21H2 patched up to the latest from earlier this week (16-MAy-2022)

## What's not working?
See above

## Job Log Output
See above

## Runner and Worker's Diagnostic Logs
See above

**Comment by ChristopherHX** [comment]
Everything is working, enshured by CI integration Tests. The only issue is that I call the following method with an in memory db ( not a Relational database ) https://github.com/ChristopherHX/runner.server/blob/a290adbe80266f68053926c5e78387752aa2314d/src/Runner.Server/Startup.cs#L126

**Comment by acotty** [comment]
Sorry, but is it a bug or am I not using the bin\Runner.Server correctly?

**Comment by ChristopherHX** [comment]
> Sorry, but is it a bug or am I not using the bin\Runner.Server correctly?

I think you are using bin\Runner.Server correctly.
If the only error is your quoted error message, then you can ignore the error message. This is no fatal error.
